package exception_handling;

public class except_handle {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
//		
//		try 
//		{
//			int b=10;
//			int c=10;
//			int sum=b+c;
//			
//			System.out.println("sum is" + sum);
//			int a=1/0;
//			System.out.println(a);
//		}
//		catch(ArithmeticException  a1)
//		{
//		  System.out.println("ArithmeticException handled");
//		}
//		finally
//		{
//			System.out.println("finally block executed");
//		}
//		
		
		String str1="Java";
		String str2="Java";
		String str3=new String("Java");
		System.out.println(str1.equals(str2) && str1.equals(str3));
		
		

	}

}
